### ISSUE TITLE
How to test the example LidarPrint.py showing points in XY format

### ISSUE THREAD

**Issue by jabrena** [jmccormack200/RPLidar#1]
Hi,

I was testing RPLidar with PiStorms, the first device starting from the left:

![image](https://pbs.twimg.com/media/CaUISVuWwAAf24u.jpg)

with your script:
https://github.com/jmccormack200/RPLidar/blob/master/LidarPrint.py

and testing a bit the Script, I update this function:

``` python
def getPoints(self,port,polar=False):
```

In order to test the way to show LIDAR info in XY format but I receive the following error:

``` bash
  File "LidarPrint.py", line 236, in <module>
    lidar = Lidar(ser)
  File "LidarPrint.py", line 60, in __init__
    self.getPoints(self.port)
  File "LidarPrint.py", line 140, in getPoints
    point = str(self.point_XY(line))
  File "LidarPrint.py", line 214, in point_XY
    circular_coordinates = point_Polar(serial_frame)
NameError: global name 'point_Polar' is not defined
```

How to test the LidarPrint.py to show LIDAR info in XY format?

**Comment by ALHarake** [comment]
Hi
I'm trying to run this code, but there is a problem with the port.write() function I assume. It causes an error (pyserial b.append(item) # this one handles int and str for our emulation and ints for Python 3.x).
However, in the "rpLIDAR interface protocol" pdf document the values for RESET and Start_Scan are the same as the ones defined in the code.
what did you do in order to solve this problem ?

**Comment by jmccormack200** [comment]
Hey sorry for not seeing this sooner. I no longer have access to the hardware to test out. If I manage to get ahold of one I'll take a look.
